- name: Update Server
  hosts: all
  become: true
  vars:
    - snmprocommunity: goodboy

  tasks:
    - name: Check snmpd.conf.orig  exists
      stat:
        path: /etc/snmp/snmpd.conf.orig
      register: stat_result

    - name: Get Backup From SNMP Config
      shell: mv /etc/snmp/snmpd.conf /etc/snmp/snmpd.conf.orig
      when: not stat_result.stat.exists

    - name: Config SNMP
      shell: echo rocommunity {{ snmprocommunity }}>> /etc/snmp/snmpd.conf
      notify: Restart snmpd

    - name: Start and Enable snmpd
      ansible.builtin.service:
        name: snmpd
        state: started
        enabled: yes

    - name: Start and Enable chronyd
      ansible.builtin.service:
        name: chronyd
        state: started
        enabled: yes

###########################################################################
#Allow Port 161 udp for SNMP on CentOS

    - name: permit snmp firewalld
      ansible.posix.firewalld:
        port: 161/udp
        permanent: yes
        state: enabled
      when: ansible_distribution == 'CentOS'

###########################################################################
#Allow Port 161 udp for SNMP on Ubuntu

    - name: permit snmp ufw
      community.general.ufw:
        rule: allow
        port: '161'
        proto: udp
      when: ansible_distribution == 'Ubuntu'

###########################################################################

  handlers:
  - name: Restart snmpd
    action: service name=snmpd state=restarted
