- name: Create User 
  hosts: all
  become: true    
  tasks:          
  - name: Create User based on a list
    user:       
     name: "{{ item }}"
     password: "{{ 'P@ss0rd' | password_hash('sha512') }}"
     shell: /bin/bash
    loop:       
      - ARA
                  
  - name: Add User on Sudo Group
    copy:       
      content: '{{ item }} ALL = (ALL) ALL'
      dest: "/etc/sudoers.d/{{item}}"
    loop:       
      - ARA
